printWidth: 120
tabWidth: 2
singleQuote: true
semi: true
arrowParens: always
trailingComma: es5
endOfLine: lf
embeddedLanguageFormatting: auto
overrides:
  - files: '*.json'
    options:
      printWidth: 100
